### ISSUE TITLE
Adapt to new twitch highlight system

### ISSUE THREAD

**Issue by fuhrmannb** [Dalet/run-highlighter#4]
Twitch has recently changed its page to manage highlights with the _Video Producer_.
run-highlighter does not work sadly on this new page =/

**Comment by Dalet** [comment]
The new system uses React and I don't know how to hook into it yet.

**Comment by Dalet** [comment]
Fixed in https://github.com/Dalet/run-highlighter/commit/ca139b1c983f914bc4729e819a41d4a026e57317
