### ISSUE TITLE
Multiple highlights on the same Twitch video

### ISSUE THREAD

**Issue by fuhrmannb** [Dalet/run-highlighter#7]
Back to #6 , the issue is still there but it is more specific: it seems that if a highlight has already been created on a stream video, the second one does not work.

[An example](https://www.twitch.tv/firemann007/manager/highlighter/300071109?start_time=8378&end_time=9282&title=TWV0YWwgU2x1ZyBNZWRpdW0gc3BlZWRydW4gaW4gMDowMCBJR1QgKDE0OjQ0IFJUQSk%3D)

**Comment by Dalet** [comment]
You can't go back and edit the time stamps anymore after you click "Create Highlights" (which the add-on clicks automatically to bring up the highlight's description form). Other than that it seems to be working.
What's happening on your end exactly?

**Comment by fuhrmannb** [comment]
On my side, the add-on does not click automatically and fill the firm strangely. See this [screenshot](https://imgur.com/a/FlAWEPc).

**Comment by Dalet** [comment]
Which browser are you using? (and which version of the browser)
________________________________

**Comment by fuhrmannb** [comment]
Chrome 68.0.3440.106 (64 bits)

**Comment by Dalet** [comment]
I tried with the same version. Any errors in the console in the developer tools (F12)? (you can right click in the middle of the console and save the entire log to a file).
Can you make me an editor on your channel so I can try your highlighter link? (I'm `Dalleth_` on Twitch)

**Comment by Dalet** [comment]
I just realized the highlighter supports `title`, `start` and `end` URL parameters natively now. The add-on might become completely optional in the future.

**Comment by Dalet** [comment]
The native URL parameters are now used.
