### ISSUE TITLE
Twitch Dashboard claims Access Denied

### ISSUE THREAD

**Issue by OliviaFairlight** [Dalet/run-highlighter#8]
Not really sure what's up with it.  It worked in the past.  Maybe something to do with the changes to the Twitch Dashboard recently?

**Comment by Dalet** [comment]
It still works for me. That would seem to indicate you're trying to highlight a video on some other channel.

Can you confirm your username is correct in your highlighter link?
![image](https://user-images.githubusercontent.com/1781420/72168463-83287380-33cd-11ea-9468-eb186c4d1b03.png)

**Comment by OliviaFairlight** [comment]
Username is correct.  Forgot Twitch is case sensitive about usernames though, and it forces all lowercase.  Running my username as all lowercase fixed it.  Might be worth making of a note of that somewhere on the site so people as dumb as I am don't run into the same issue?  ;)

**Comment by Dalet** [comment]
I didn't know about the case sensitivity! I'll make it convert to all lowercase.
Thank you.
