### ISSUE TITLE
Can't find video in the archives of this channel

### ISSUE THREAD

**Issue by fuhrmannb** [Dalet/run-highlighter#9]
I'm trying to use the tool connected to my Twitch channel and I have the following message error:

```
Not found

The run was not found in the archives of this channel.
The video archive may have expired. 
```

The tool should normally find the run in this video: https://www.twitch.tv/videos/1682468054

Screenshot:

![image](https://user-images.githubusercontent.com/19579566/208486994-bb03b762-8229-4059-a061-24112733102f.png)

JS Console output:

```
18:39:43.621 InstallTrigger is deprecated and will be removed in the future. [constants.js:50:14](moz-extension://68454bd7-7673-4180-8354-3118edf5d53d/constants.js)
18:39:43.647 Failed to get subsystem status for purpose 
Object { rejected: true, message: TypeError }
[content-script.js:95:21](moz-extension://68454bd7-7673-4180-8354-3118edf5d53d/content-script.js)
18:39:45.889 Empty string passed to getElementById(). 8 [autofill.js:159:12](moz-extension://1c2fe9fa-d635-41be-80b7-dc79e558ce43/content/autofill.js)
18:40:37.399 Run Highlighter: parsing segment history... [entry-72ed921d.mjs:35:24573](https://dalet.github.io/run-highlighter/_nuxt/entry-72ed921d.mjs)
18:40:37.409 Run Highlighter: Stopped traversing segment history after 20 entries [entry-72ed921d.mjs:35:25067](https://dalet.github.io/run-highlighter/_nuxt/entry-72ed921d.mjs)
18:40:37.410 Run Highlighter: getHistory() took 10ms [entry-72ed921d.mjs:35:25194](https://dalet.github.io/run-highlighter/_nuxt/entry-72ed921d.mjs)
18:41:13.203 Empty string passed to getElementById(). 10 [run-highlighter](https://dalet.github.io/run-highlighter/)
```

**Comment by Dalet** [comment]
Thanks for the report.
Can you send me your splits file so that I can reproduce this?

**Comment by fuhrmannb** [comment]
[Neon White - White's Heaven Rush.zip](https://github.com/Dalet/run-highlighter/files/10290214/Neon.White.-.White.s.Heaven.Rush.zip)

**Comment by Dalet** [comment]
The fix is now deployed. Sorry for the delay!

**Comment by fuhrmannb** [comment]
Thanks for the fix, but I think I hit the problem again (or maybe another problem) =/

See new attached splits: [Lovely Planet - All Levels.zip](https://github.com/Dalet/run-highlighter/files/10808853/Lovely.Planet.-.All.Levels.zip)

**Comment by Dalet** [comment]
Which browser do you use? It's working for me on Chrome and Firefox.
![image](https://user-images.githubusercontent.com/1781420/220803550-678a6dde-b2ba-47de-8c68-8374d28ffb70.png)

**Comment by fuhrmannb** [comment]
I've tested on both Firefox & Chrome with my account, same issue each time. Also tested in private mode.

In the console log, I have the following warning:

```
Empty string passed to getElementById().
```

I can't test in demo mode since I can't perform a search in it.
